create new hardhat project
ShenaniganDApp/shenanigan-monorepo pull request #168
Opened 2021-03-26 03:17 UTC by ezynda3

create vscode workspace

fix compiler recommendations

add deployment scripts

This is a big commit but only because I copied the contracts over from the buidler package. This should be merged so I can contiue with the Factory contract.

2021-03-26 04:06 UTC, youngkidwarrior requested changes

2021-03-26 04:06 UTC, youngkidwarrior commented on packages/hardhat/hardhat.config.ts
> +/* eslint-disable import/no-extraneous-dependencies */
I noticed this file is much smaller than the buidler file. This is bound to break some commands in the monorepo package.json. 

Can you comment out the broken commands and add TODOs

2021-03-31 03:49 UTC, ezynda3 commented
Should be fixed now

2021-04-02 06:10 UTC, youngkidwarrior commented
@ezynda3 looks good!

There seems to be a conflict with your yarn.lock.

2021-04-02 06:12 UTC, youngkidwarrior submitted a review, later dismissed

2021-04-02 22:41 UTC, merged

2021-04-08 06:55 UTC, youngkidwarrior commented
@ezynda3 the factory contract looks good

Tasks left to be done:

* Remove deprecated buidler folder
* Add these commands for hardhat into `package.json` and finish the TODOs
```  "scripts": {
    "chain": "buidler node",
    "test": "buidler test --network buidlerevm",
    "compile": "buidler compile",
    "deploy": "buidler run scripts/deploy.js --show-stack-traces && buidler run scripts/publish.js",
    "watch": "node scripts/watch.js",
    "accounts": "buidler accounts",
    "balance": "buidler balance",
    "send": "buidler send"
  }```
  
  * Fix problems with Ownership on Facets

This should be contained in another PR that merges into this one before we merge to master. This will still count as 2 PRs in sourcecreds eyes