create factory contract
ShenaniganDApp/shenanigan-monorepo pull request #184
Opened 2021-04-05 07:46 UTC by ezynda3

Here is the Diamond Factory Deployer. Basically the constructor takes all the arguments that your original diamond would take and then diamonds will be deployed with those arguments.

2021-04-09 15:16 UTC, youngkidwarrior commented
Contract looks good. There are a couple changes that still need to be made in the pipeline.

- Update the commands in the monorepo `package.json` to use hardhat
- Remove deprecated buidler folder
- Add these commands back to the hardhat `package.json`
```
  "scripts": {
    "chain": "buidler node",
    "test": "buidler test --network buidlerevm",
    "compile": "buidler compile",
    "deploy": "buidler run scripts/deploy.js --show-stack-traces && buidler run scripts/publish.js",
    "watch": "node scripts/watch.js",
    "accounts": "buidler accounts",
    "balance": "buidler balance",
    "send": "buidler send"
  }
```
- Fix all the @TODO in hardhat.config.js

Feel free to make a separate PR that merges into this branch for these changes

2021-04-09 15:17 UTC, youngkidwarrior requested changes
Contract looks good. There are a couple changes that still need to be made in the pipeline.

Update the commands in the monorepo package.json to use hardhat
Remove deprecated buidler folder
Add these commands back to the hardhat package.json
  "scripts": {
    "chain": "buidler node",
    "test": "buidler test --network buidlerevm",
    "compile": "buidler compile",
    "deploy": "buidler run scripts/deploy.js --show-stack-traces && buidler run scripts/publish.js",
    "watch": "node scripts/watch.js",
    "accounts": "buidler accounts",
    "balance": "buidler balance",
    "send": "buidler send"
  }
Fix all the @todo in hardhat.config.js
Feel free to make a separate PR that merges into this branch for these changes

2021-04-11 04:22 UTC, ezynda3 commented
Should be good to go now

2021-04-12 15:32 UTC, youngkidwarrior approved these changes

2021-04-12 15:32 UTC, merged