User challenges list styling
ShenaniganDApp/shenanigan-monorepo pull request #373
Opened 2021-08-09 15:54 UTC by prasadwalvekar

### Changes

- Add styles for User Challenges List screen

### Screenshot

<img width="488" alt="Screenshot 2021-08-09 at 9 15 06 PM" src="https://user-images.githubusercontent.com/4965435/128736001-77e40222-3e0e-42d6-a757-40236eb3b035.png">

2021-08-10 18:37 UTC, stormcloud266 requested changes
Everything looks really good! Thank you.

2021-08-10 18:37 UTC, stormcloud266 commented on packages/app/src/components/profile/UserChallengesList.tsx
> +        margin: '5% 0%'
This syntax causes an error for me. `marginVertical: '5%'` would work here.

2021-08-10 18:37 UTC, stormcloud266 commented on packages/app/src/components/profile/UserChallengesList.tsx
> +        backgroundColor: 'rgba(255, 255, 255, 0.5)'
Let's add `flex: 1` here to pull the background all the way done even without any list items. I saw that I missed this in the market list as well and will be updating it. 

![Screen Shot 2021-08-10 at 12 11 03 PM](https://user-images.githubusercontent.com/19338130/128916135-0a3fff81-927c-4135-bf1c-ad29139bf395.png)

2021-08-11 08:45 UTC, prasadwalvekar commented
Code review changes done.

2021-08-11 14:49 UTC, stormcloud266 approved these changes

2021-08-11 19:27 UTC, merged